In [24]:
import pandas as pd

In [25]:
import requests

In [34]:
url = 'https://brasilapi.com.br/api/ncm/v1?search'
response = requests.get(url)

In [35]:
if response.status_code == 200:
    data_json = response.json()
else:
    print('Erro ao acessar a API')

In [36]:
data = response.json()

In [38]:
NCM = pd.DataFrame(data_json)
NCM

,codigo,descricao,data_inicio,data_fim,tipo_ato,numero_ato,ano_ato
0,01,Animais vivos.,2022-04-01,9999-12-31,Res Camex,272,2021
1,01.01,"Cavalos, asininos e muares, vivos.",2022-04-01,9999-12-31,Res Camex,272,2021
2,0101.2,- Cavalos:,2022-04-01,9999-12-31,Res Camex,272,2021
3,0101.21.00,-- Reprodutores de raça pura,2022-04-01,9999-12-31,Res Camex,272,2021
4,0101.29.00,-- Outros,2022-04-01,9999-12-31,Res Camex,272,2021
...,...,...,...,...,...,...,...
15136,9705.31.00,-- Com mais de 100 anos,2022-04-01,9999-12-31,Res Camex,272,2021
15137,9705.39.00,-- Outras,2022-04-01,9999-12-31,Res Camex,272,2021
15138,97.06,Antiguidades com mais de 100 anos.,2022-04-01,9999-12-31,Res Camex,272,2021
15139,9706.10.00,- Com mais de 250 anos,2022-04-01,9999-12-31,Res Camex,272,2021
15140,9706.90.00,- Outras,2022-04-01,9999-12-31,Res Camex,272,2021

In [39]:
url = 'https://brasilapi.com.br/api/pix/v1/participants'
response = requests.get(url)

In [40]:
if response.status_code == 200:
    data_json = response.json()
else:
    print('Erro ao acessar a API')

In [41]:
data = response.json()

In [42]:
PIX = pd.DataFrame(data_json)
PIX

,ispb,nome,nome_reduzido,modalidade_participacao,tipo_participacao,inicio_operacao
0,00000000,BANCO DO BRASIL S.A.,BCO DO BRASIL S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
1,00000208,BRB - BANCO DE BRASILIA S.A.,BRB - BCO DE BRASILIA S.A.,PDCT,DRCT,2020-11-03T09:30:00.000Z
2,00068987,COOPERATIVA DE CRÉDITO ARACREDI LTDA. - SICOOB...,CC ARACREDI LTDA.,PDCT,IDRT,2020-11-03T09:30:00.000Z
3,00075847,COOPERATIVA DE CRÉDITO UNICRED CENTRO-SUL LTDA...,CC UNICRED CENTRO-SUL LTDA - UNICRED CENTRO-SUL,PDCT,IDRT,2020-11-03T09:30:00.000Z
4,00106180,CENTRAL DAS COOPERATIVAS DE CRÉDITO DOS ESTADO...,"CCC DOS EST DE MT, MS E MUN DE CACOAL/RO",PDCT,IDRT,2020-11-03T09:30:00.000Z
...,...,...,...,...,...,...
889,95213211,"COOPERATIVA DE CRéDITO, POUPANçA E INVESTIMENT...",COOP SICREDI CAMINHO DAS ÁGUAS RS,PDCT,IDRT,2020-11-03T09:30:00.000Z
890,95424891,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI VALE DO RIO PARDO,PDCT,IDRT,2020-11-03T09:30:00.000Z
891,95594941,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI REG CENTRO RS/MG,PDCT,IDRT,2020-11-03T09:30:00.000Z
892,97259253,COOPERATIVA E ECONOMIA E CRÉDITO MÚTUO DOS MÉD...,CECM MÉDICOS PLANALTO MÉDIO RS - CREDISIS/CRED...,PDCT,IDRT,2021-10-04T12:53:10.567Z
893,97489280,"COOPERATIVA DE CRÉDITO, POUPANÇA E INVESTIMENT...",COOP SICREDI INTEGRAÇÃO BAHIA,PDCT,IDRT,2020-11-03T09:30:00.000Z

In [48]:
url = 'https://brasilapi.com.br/api/banks/v1'
response = requests.get(url)

In [49]:
if response.status_code == 200:
    data_json = response.json()
else:
    print('Erro ao acessar a API')

In [50]:
data = response.json()

In [51]:
BANCOS = pd.DataFrame(data_json)
BANCOS

,ispb,name,code,fullName
0,00000000,BCO DO BRASIL S.A.,1.0,Banco do Brasil S.A.
1,00000208,BRB - BCO DE BRASILIA S.A.,70.0,BRB - BANCO DE BRASILIA S.A.
2,00038121,Selic,NaN,Banco Central do Brasil - Selic
3,00038166,Bacen,NaN,Banco Central do Brasil
4,00122327,SANTINVEST S.A. - CFI,539.0,"SANTINVEST S.A. - CREDITO, FINANCIAMENTO E INV..."
...,...,...,...,...
354,92875780,WARREN CVMC LTDA,371.0,WARREN CORRETORA DE VALORES MOBILIÁRIOS E CÂMB...
355,92894922,BANCO ORIGINAL,212.0,Banco Original S.A.
356,94968518,EFX CC LTDA.,289.0,EFX CORRETORA DE CÂMBIO LTDA.
357,,NaN,NaN,NaN
358,,NaN,NaN,NaN

In [52]:
pip install plyer

Requirement already satisfied: plyer in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (2.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from plyer import notification
notification.notify(
title='Erro',
message='Houve um erro ao acessar a API',
app_name='NCM',
timeout=10
)

In [57]:
from plyer import notification
notification.notify(
title='Erro',
message='Houve um erro ao acessar a API',
app_name='pix',
timeout=10
)

In [58]:
from plyer import notification
notification.notify(
title='Erro',
message='Houve um erro ao acessar a API',
app_name='BANCO',
timeout=10
)